version: '3'

services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
