version: '3'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=merchandise
      - POSTGRES_USER=merch
      - POSTGRES_PASSWORD=merch2023!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: