spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/merchandise
    username: merch
    password: merch2023!

  flyway:
    baseline-on-migrate: true


jwt:
  secret: bXlKV1Qtc2VjcmV0LWtleS0yMDIzLUFVLTAwOTEwLVh+IUAh
  expiration: 3600

logging:
  level:
    root: warn
    org.springframework: INFO
    my.playground.onlineshop: DEBUG