#!/bin/bash

# Ensure the script fails on any error
set -e

# Use Docker Compose to bring up the testing environment and run tests
docker-compose -f docker-compose.test.yml up --build --exit-code-from app-test

# Clean up the testing environment after tests are done
docker-compose -f docker-compose.test.yml down
